version: '3.5'

services:

  banking-app:
    container_name: banking-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
      - '4242:4242'
    environment:
      - NODE_ENV=development
